first_name = input("請輸入姓 : ")
print()
last_name = input("請輸入名 : ")
print()
score_1 = input("請輸入計算機概論成績 : ")
print()
score_2 = input("請輸入程式設計成績 : ")
print(first_name+last_name)
print(int(score_1) +" "+ int(score_2))
print((int(score_2)+int(score_1))/2)